vich_uploader:
    db_driver: orm
    mappings:
        livre_cover_image:
            uri_prefix: /images/covers
            upload_destination: '%kernel.project_dir%/public/images/covers'
            #allow_overwrite: false
            delete_on_remove: true
            delete_on_update: true
