
vich_uploader:
    db_driver: orm
    mappings:
        front_cover_upload:
            uri_prefix: /uploads/books/frontcovers
            upload_destination: '%kernel.project_dir%/public/uploads/books/frontcovers'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer

        back_cover_upload:
            uri_prefix: /uploads/books/backcovers
            upload_destination: '%kernel.project_dir%/public/uploads/books/backcovers'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer

