controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
  path: /login
  methods: ['POST']

abonnement:
  path: /abonnements/create
  controller: App\Controller\CreateAbonnementController::createAbonnement
  methods: [POST]

emprunter_Book:
  path: /emprunter/create
  controller: App\Controller\EmpruntController::borrow
  methods: [POST]


